version: '3.8'

services:
  # Dịch vụ MySQL
  mysql:
    image: mysql:8.0
    container_name: ${MYSQL_CONTAINER_NAME:-quizme-mysql}
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-quizme_db}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-''}
      MYSQL_ALLOW_EMPTY_PASSWORD: ${MYSQL_ALLOW_EMPTY_PASSWORD:-"yes"}
      MYSQL_USER: ${MYSQL_USER:-quizme_user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-quizme_password}
    ports:
      - "${MYSQL_PORT:-3307}:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./src/main/resources/sql:/docker-entrypoint-initdb.d
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - quizme-network

  # Dịch vụ phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ${PHPMYADMIN_CONTAINER_NAME:-quizme-phpmyadmin}
    environment:
      PMA_HOST: ${MYSQL_HOST:-mysql}
      PMA_PORT: ${MYSQL_CONTAINER_PORT:-3306}
      PMA_USER: ${MYSQL_USER:-root}
      PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD:-''}
      UPLOAD_LIMIT: ${PHPMYADMIN_UPLOAD_LIMIT:-100M}
    ports:
      - "${PHPMYADMIN_PORT:-8081}:80"
    depends_on:
      - mysql
    restart: unless-stopped
    networks:
      - quizme-network

  # Dịch vụ ứng dụng Spring Boot
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: ${APP_CONTAINER_NAME:-quizme-app}
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://${MYSQL_HOST:-mysql}:${MYSQL_CONTAINER_PORT:-3306}/${MYSQL_DATABASE:-quizme_db}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME:-root}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD:-''}
      SPRING_JPA_HIBERNATE_DDL_AUTO: ${SPRING_JPA_HIBERNATE_DDL_AUTO:-update}
      SPRING_JPA_SHOW_SQL: ${SPRING_JPA_SHOW_SQL:-true}
      SERVER_PORT: ${SERVER_PORT:-8080}
      # Thêm các biến môi trường khác nếu cần
    ports:
      - "${APP_PORT:-8080}:${SERVER_PORT:-8080}"
    restart: unless-stopped
    networks:
      - quizme-network

# Volume để lưu trữ dữ liệu MySQL
volumes:
  mysql-data:
    name: ${MYSQL_VOLUME_NAME:-quizme-mysql-data}

# Network cho các dịch vụ
networks:
  quizme-network:
    name: ${NETWORK_NAME:-quizme-network}
    driver: bridge